workflows:
  android-release:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.19.0
    scripts:
      - name: Get dependencies
        script: cd sum-grid-app-main && flutter pub get
      - name: Build APK
        script: cd sum-grid-app-main && flutter build apk --release
    artifacts:
      - sum-grid-app-main/build/app/outputs/flutter-apk/app-release.apk